// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.2
// source: scrooge_request.proto

package scrooge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message with data to make the scrooge application do an action
type ScroogeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*ScroogeRequest_SendMessageRequest
	//	*ScroogeRequest_SetClusterConfigRequest
	//	*ScroogeRequest_AuthenticateMessageRequest
	Request isScroogeRequest_Request `protobuf_oneof:"request"`
}

func (x *ScroogeRequest) Reset() {
	*x = ScroogeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scrooge_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScroogeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScroogeRequest) ProtoMessage() {}

func (x *ScroogeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrooge_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScroogeRequest.ProtoReflect.Descriptor instead.
func (*ScroogeRequest) Descriptor() ([]byte, []int) {
	return file_scrooge_request_proto_rawDescGZIP(), []int{0}
}

func (m *ScroogeRequest) GetRequest() isScroogeRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ScroogeRequest) GetSendMessageRequest() *SendMessageRequest {
	if x, ok := x.GetRequest().(*ScroogeRequest_SendMessageRequest); ok {
		return x.SendMessageRequest
	}
	return nil
}

func (x *ScroogeRequest) GetSetClusterConfigRequest() *SetClusterConfigRequest {
	if x, ok := x.GetRequest().(*ScroogeRequest_SetClusterConfigRequest); ok {
		return x.SetClusterConfigRequest
	}
	return nil
}

func (x *ScroogeRequest) GetAuthenticateMessageRequest() *AuthenticateMessageRequest {
	if x, ok := x.GetRequest().(*ScroogeRequest_AuthenticateMessageRequest); ok {
		return x.AuthenticateMessageRequest
	}
	return nil
}

type isScroogeRequest_Request interface {
	isScroogeRequest_Request()
}

type ScroogeRequest_SendMessageRequest struct {
	SendMessageRequest *SendMessageRequest `protobuf:"bytes,1,opt,name=send_message_request,json=sendMessageRequest,proto3,oneof"`
}

type ScroogeRequest_SetClusterConfigRequest struct {
	SetClusterConfigRequest *SetClusterConfigRequest `protobuf:"bytes,2,opt,name=set_cluster_config_request,json=setClusterConfigRequest,proto3,oneof"`
}

type ScroogeRequest_AuthenticateMessageRequest struct {
	AuthenticateMessageRequest *AuthenticateMessageRequest `protobuf:"bytes,3,opt,name=authenticate_message_request,json=authenticateMessageRequest,proto3,oneof"`
}

func (*ScroogeRequest_SendMessageRequest) isScroogeRequest_Request() {}

func (*ScroogeRequest_SetClusterConfigRequest) isScroogeRequest_Request() {}

func (*ScroogeRequest_AuthenticateMessageRequest) isScroogeRequest_Request() {}

// Message to make scrooge send a message to another RSM over the scrooge protocol
type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier of which cluster to send this message on
	ClusterIdentifier *ClusterIdentifier `protobuf:"bytes,1,opt,name=cluster_identifier,json=clusterIdentifier,proto3" json:"cluster_identifier,omitempty"`
	// The content and scrooge bookkeeping logic needed by scrooge for correctness
	Content *CrossChainMessageData `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// A proof generated by the entire RSM proving that the message contents are valid
	// and intended for the `cluster_identifier` RSM
	ValidityProof []byte `protobuf:"bytes,3,opt,name=validity_proof,json=validityProof,proto3" json:"validity_proof,omitempty"`
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scrooge_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrooge_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_scrooge_request_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetClusterIdentifier() *ClusterIdentifier {
	if x != nil {
		return x.ClusterIdentifier
	}
	return nil
}

func (x *SendMessageRequest) GetContent() *CrossChainMessageData {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageRequest) GetValidityProof() []byte {
	if x != nil {
		return x.ValidityProof
	}
	return nil
}

// Message to make scrooge update its internal idea of a network configuration
type SetClusterConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Configuration to be put in place
	ClusterConfiguration *ClusterConfiguration `protobuf:"bytes,1,opt,name=cluster_configuration,json=clusterConfiguration,proto3" json:"cluster_configuration,omitempty"`
}

func (x *SetClusterConfigRequest) Reset() {
	*x = SetClusterConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scrooge_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetClusterConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClusterConfigRequest) ProtoMessage() {}

func (x *SetClusterConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrooge_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClusterConfigRequest.ProtoReflect.Descriptor instead.
func (*SetClusterConfigRequest) Descriptor() ([]byte, []int) {
	return file_scrooge_request_proto_rawDescGZIP(), []int{2}
}

func (x *SetClusterConfigRequest) GetClusterConfiguration() *ClusterConfiguration {
	if x != nil {
		return x.ClusterConfiguration
	}
	return nil
}

type AuthenticateMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier of the message in question
	MessageIdentifier *MessageIdentifier `protobuf:"bytes,1,opt,name=message_identifier,json=messageIdentifier,proto3" json:"message_identifier,omitempty"`
	// whether to accept or reject the message, default is reject
	AcceptMessage bool `protobuf:"varint,2,opt,name=accept_message,json=acceptMessage,proto3" json:"accept_message,omitempty"`
}

func (x *AuthenticateMessageRequest) Reset() {
	*x = AuthenticateMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scrooge_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateMessageRequest) ProtoMessage() {}

func (x *AuthenticateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrooge_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateMessageRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateMessageRequest) Descriptor() ([]byte, []int) {
	return file_scrooge_request_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateMessageRequest) GetMessageIdentifier() *MessageIdentifier {
	if x != nil {
		return x.MessageIdentifier
	}
	return nil
}

func (x *AuthenticateMessageRequest) GetAcceptMessage() bool {
	if x != nil {
		return x.AcceptMessage
	}
	return false
}

var File_scrooge_request_proto protoreflect.FileDescriptor

var file_scrooge_request_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65,
	0x1a, 0x15, 0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65,
	0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb6, 0x02, 0x0a, 0x0e, 0x53, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x14, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x12, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5f, 0x0a, 0x1a, 0x73, 0x65, 0x74, 0x5f, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x63, 0x72, 0x6f,
	0x6f, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x17, 0x73,
	0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x67, 0x0a, 0x1c, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73,
	0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x1a, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc0, 0x01, 0x0a, 0x12, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x49, 0x0a, 0x12, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x11, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x6d, 0x0a,
	0x17, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x52, 0x0a, 0x15, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67,
	0x65, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8e, 0x01, 0x0a,
	0x1a, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x12, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67,
	0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x52, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0a, 0x5a,
	0x08, 0x2f, 0x73, 0x63, 0x72, 0x6f, 0x6f, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_scrooge_request_proto_rawDescOnce sync.Once
	file_scrooge_request_proto_rawDescData = file_scrooge_request_proto_rawDesc
)

func file_scrooge_request_proto_rawDescGZIP() []byte {
	file_scrooge_request_proto_rawDescOnce.Do(func() {
		file_scrooge_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_scrooge_request_proto_rawDescData)
	})
	return file_scrooge_request_proto_rawDescData
}

var file_scrooge_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scrooge_request_proto_goTypes = []interface{}{
	(*ScroogeRequest)(nil),             // 0: scrooge.ScroogeRequest
	(*SendMessageRequest)(nil),         // 1: scrooge.SendMessageRequest
	(*SetClusterConfigRequest)(nil),    // 2: scrooge.SetClusterConfigRequest
	(*AuthenticateMessageRequest)(nil), // 3: scrooge.AuthenticateMessageRequest
	(*ClusterIdentifier)(nil),          // 4: scrooge.ClusterIdentifier
	(*CrossChainMessageData)(nil),      // 5: scrooge.CrossChainMessageData
	(*ClusterConfiguration)(nil),       // 6: scrooge.ClusterConfiguration
	(*MessageIdentifier)(nil),          // 7: scrooge.MessageIdentifier
}
var file_scrooge_request_proto_depIdxs = []int32{
	1, // 0: scrooge.ScroogeRequest.send_message_request:type_name -> scrooge.SendMessageRequest
	2, // 1: scrooge.ScroogeRequest.set_cluster_config_request:type_name -> scrooge.SetClusterConfigRequest
	3, // 2: scrooge.ScroogeRequest.authenticate_message_request:type_name -> scrooge.AuthenticateMessageRequest
	4, // 3: scrooge.SendMessageRequest.cluster_identifier:type_name -> scrooge.ClusterIdentifier
	5, // 4: scrooge.SendMessageRequest.content:type_name -> scrooge.CrossChainMessageData
	6, // 5: scrooge.SetClusterConfigRequest.cluster_configuration:type_name -> scrooge.ClusterConfiguration
	7, // 6: scrooge.AuthenticateMessageRequest.message_identifier:type_name -> scrooge.MessageIdentifier
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_scrooge_request_proto_init() }
func file_scrooge_request_proto_init() {
	if File_scrooge_request_proto != nil {
		return
	}
	file_scrooge_message_proto_init()
	file_scrooge_networking_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_scrooge_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScroogeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scrooge_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scrooge_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetClusterConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scrooge_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticateMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_scrooge_request_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ScroogeRequest_SendMessageRequest)(nil),
		(*ScroogeRequest_SetClusterConfigRequest)(nil),
		(*ScroogeRequest_AuthenticateMessageRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scrooge_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scrooge_request_proto_goTypes,
		DependencyIndexes: file_scrooge_request_proto_depIdxs,
		MessageInfos:      file_scrooge_request_proto_msgTypes,
	}.Build()
	File_scrooge_request_proto = out.File
	file_scrooge_request_proto_rawDesc = nil
	file_scrooge_request_proto_goTypes = nil
	file_scrooge_request_proto_depIdxs = nil
}
